// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZuPbvcEzGC0RmKlCeQ_n-976xqvEGUQ8',
    appId: '1:844567794669:android:635c51a543e15c57784de4',
    messagingSenderId: '844567794669',
    projectId: 'looknote',
    storageBucket: 'looknote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CjgFM1nNJ0aivFG1IxvBeAxkrZz1AjA',
    appId: '1:844567794669:ios:43716b929b8e694b784de4',
    messagingSenderId: '844567794669',
    projectId: 'looknote',
    storageBucket: 'looknote.appspot.com',
    iosClientId: '844567794669-qsraudv9jfjq3rfvdqe13m6kcpt02rfk.apps.googleusercontent.com',
    iosBundleId: 'kr.co.befferent.looknote',
  );
}
